### ISSUE TITLE
Open in browser in background not working with Chrome

### ISSUE THREAD

**Issue by lisandrovico** [brentsimmons/NetNewsWire#905]
I've tried with double click, enter and from the right click contextual menu. I tried unsetting and setting back again the preference to open in background with no effect.

**Comment by williamw** [comment]
+1 

Would like to see this fixed. I use Chrome as my default browser at work, and Safari as my personal browser — just to keep some work-life balance.

**Comment by Wevah** [comment]
I think this is the same issue as is affecting Brave in #1302.

**Comment by shazron** [comment]
This is the Chromium bug to follow (star that issue): https://bugs.chromium.org/p/chromium/issues/detail?id=854609
Looks like it's a WIP, there was a patch but it broke tests and I don't believe anyone is assigned to it currently based on the comments.

**Comment by nskh** [comment]
This seems to be fixed in the latest version of Chrome: 110.0.5481.77 on Mac, for me at least

**Comment by shazron** [comment]
Yay!
Tested on NNW 6.1:
Confirmed fixed in macOS Chrome 110.0.5481.100 (arm64)
Confirmed fixed in macOS Edge 110.0.1587.41 (arm64)
Confirmed fixed in macOS Firefox 110.0 (64-bit)
Confirmed fixed in macOS Brave [Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (arm64)](https://brave.com/latest/)
Didn't test Chromium but it's a safe bet it works since 3/4 of the browsers are Chromium based

**Comment by shazron** [comment]
Alas, looking at the comment here, the Chromium "fix" was reverted a day ago 😭 
https://bugs.chromium.org/p/chromium/issues/detail?id=1385436#c24

**Comment by synyan** [comment]
> Alas, looking at the comment here, the Chromium "fix" was reverted a day ago 😭
> https://bugs.chromium.org/p/chromium/issues/detail?id=1385436#c24

this is so far the most annoying problem for me.

**Comment by jms1voalte** [comment]
"Open in background" still not working with Brave. `[Version 1.60.114 Chromium: 119.0.6045.124 (Official Build) (x86_64)](https://brave.com/latest/)`

**Comment by avtraino** [comment]
Until this is fixed by the Chromium team, I'm working around it with a Keyboard Maestro macro:

https://forum.keyboardmaestro.com/t/netnewswire-open-in-background-workaround-for-chromium-bug/34047

**Comment by brentsimmons** [comment]
It’s unfortunate that this bug is still open.

**Comment by kg4zow** [comment]
> It’s unfortunate that this bug is still open.

Leave it to google to *never* pass up an opportunity to shove their browser to the top. Gotta show those ads!

**Comment by shazron** [comment]
The Chromium bug I referenced above was closed and "duped" into https://bugs.chromium.org/p/chromium/issues/detail?id=1385436 (still Open) and the last it got a comment was May 25, 2023...

**Comment by brentsimmons** [comment]
Unfortunately, this bug isn’t something we can fix. It’s up to the Chromium folks.
